### ISSUE TITLE
What role(s) need to be added to a user for clicking between Business Table tabs?

### ISSUE THREAD

**Issue by jdownsameresco** [VolkovLabs/business-table#303]
### Your Question

What role(s) need to be added to a user for clicking between Business Table tabs?

### Context and Details

I have 2 tabs in a business table.  We just upgraded to grafana 11.6 and after the upgrade, our user that had minimal roles can no longer click on the second tab of a business table without getting this error (they could access prior to the upgrade):  

Error
user-storage.userstorage.grafana.app is forbidden: User "user" cannot create resource "user-storage" in API group "userstorage.grafana.app" in the namespace "default": Grafana org role (None) didn't allow create access on requested resource=user-storage, path=/apis/userstorage.grafana.app/v0alpha1/namespaces/default/user-storage/

Subsequent clicks between tabs result in the following error:

Error
user-storage.userstorage.grafana.app "volkovlabs-table-panel:u000000025" not found

### Environment (if applicable)

Plugin version: 2.5.0
Grafana version: 11.6
Datasource: Postgres

**Comment by mikhail-vl** [comment]
@jdownsameresco User Preferences is one of the newest features in the Grafana 11.5 and we incorporated it in the Business Table panel to keep user specific customization.

  Are you using Grafana Community or Enterprise version? User needs to be logged in for user preferences to work.

**Comment by jdownsameresco** [comment]
@mikhail-vl We are using Enterprise version.  The user is logged in through jwt, but doesn't have the basic viewer, or editor role, just what they need to view the dashboards, I assume there is fixed role that we must be missing?

**Comment by mikhail-vl** [comment]
@jdownsameresco That's a great question. We don't have Grafana Enterprise version and because the feature is new, I have not seen any discussions about it in the Grafana Forum or community slack.

  I quickly checked in Grafana Cloud and can't find what I was looking for. I asked in the Grafana Community Slack channel. I am waiting for Grafana Core team to respond.

  Meanwhile, I would recommend to check with Grafana support and please let me know if you got it resolved.

**Comment by DenicBerthold** [comment]
Hello, we have the same issue with Grafana On Premise (no Enterprise).

User is logged in via LDAP and has Basic View rights to the Dashboard.

**Comment by DenicBerthold** [comment]
HI @mikhail-vl 

we are currently at release [Grafana v12.0.0 (4c0e7045f9)](https://github.com/grafana/grafana/blob/main/CHANGELOG.md) so i didn´t see if in 12.01 or 12.02 it is fixed.

**Comment by DenicBerthold** [comment]
Hi @mikhail-vl i did test it yesterday with 12.0.2 and the issue is still repeatable.

So no fix on grafana side.

**Comment by vitPinchuk** [comment]
@DenicBerthold 
Thank you for your question!

At the moment, we’re also noticing that the update related to this feature is still not available in version 12.0.2. We’ll keep an eye on future releases, and as soon as it becomes available, we’ll let you know.

Thanks again! 🙌

**Comment by mikhail-vl** [comment]
Based on the Grafana's team feedback, update will be included in the Grafana 12.1.
